### PR TITLE
update to latest CC branch

### PR DESCRIPTION
**Pull request by valentt**

### CODE REVIEW

**Comment by kostko** [comment]
Have you tested if everything builds in this branch?

**Comment by kostko** [comment]
Ping?

**Comment by kostko** [comment]
BTW, I see that you forgot to regenerate the Dockerfiles. When you change the OpenWrt release, you must also run `./openwrt/scripts/generate-dockerfiles` to update the Dockerfiles, which you then also commit into the repository.

**Comment by mitar** [comment]
>  When you change the OpenWrt release, you must also run ./openwrt/scripts/generate-dockerfiles to update the Dockerfiles, which you then also commit into the repository.

Is this documented anywhere? :-)

**Comment by kostko** [comment]
Currently not. It should be added into the existing README or a part of it should be split into its own documentation.

**Comment by mitar** [comment]
I think README is good for now. The main thing is that it should be documented.

**Comment by kostko** [comment]
I have now added a [section to the README file](https://github.com/wlanslovenija/firmware-core#updating-the-openwrt-build-system).

The latest updates add preliminary support for OpenWRT DD (master). This conflicts with the current PR, so please rebase it on updated master.

**Comment by kostko** [comment]
Bumped in b61f74041ea48b9751117beb89eb6f2181b3b84b.

**Pull request closed without merging**
